/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "./tests/_main.check" instead.
 */

#include <check.h>

#include <stdio.h>
#include <string.h>
#include "string_functions/s21_string.h"

START_TEST(s21_memchr_empty_str)
{
  s21_size_t nByte = 0;
  char testStr[10] = "";
  int findByte = '\0';

  void *expected = memchr(testStr, findByte, nByte);
  void *actual = s21_memchr(testStr, findByte, nByte);

  ck_assert_ptr_eq(expected, actual);

}
END_TEST

START_TEST(s21_memchr_find_zero_in_stringt)
{
  s21_size_t nByte = 5;
  char testStr[5] = "Hello";
  int findByte = '\0';

  void *expected = memchr(testStr, findByte, nByte);
  void *actual = s21_memchr(testStr, findByte, nByte);

  ck_assert_ptr_eq(expected, actual);

}
END_TEST

START_TEST(s21_memchr_find_simbol_in_string_in_start)
{
  s21_size_t nByte = 5;
  char testStr[5] = "World";
  int findByte = 'W';

  void *expected = memchr(testStr, findByte, nByte);
  void *actual = s21_memchr(testStr, findByte, nByte);

  ck_assert_ptr_eq(expected, actual);

}
END_TEST

START_TEST(s21_memchr_find_simbol_in_string_in_end)
{
  s21_size_t nByte = 6;
  char testStr[11] = "Hello World";
  int findByte = 'd';

  void *expected = memchr(testStr, findByte, nByte);
  void *actual = s21_memchr(testStr, findByte, nByte);

  ck_assert_ptr_eq(expected, actual);

}
END_TEST

START_TEST(s21_memchr_test_memchr_not_found)
{
  s21_size_t nByte = 5;
  char testStr[5] = "Hello";
  int findByte = 'x';

  void *expected = memchr(testStr, findByte, nByte);
  void *actual = s21_memchr(testStr, findByte, nByte);

  ck_assert_ptr_eq(expected, actual);
}
END_TEST

START_TEST(s21_memcmp_zero_byte)
{
  s21_size_t nByte = 0;
  char dataStr1[] = "Hello";
  char dataStr2[] = "Hello";

  int expected = memcmp(dataStr1, dataStr2, nByte);
  int actual = s21_memcmp(dataStr1, dataStr2, nByte);

  ck_assert_int_eq(expected, actual);



}
END_TEST

START_TEST(s21_memcmp_positive_test)
{
  s21_size_t nByte = 5;
  char dataStr1[] = "Hello";
  char dataStr2[] = "Hello";

  int expected = memcmp(dataStr1, dataStr2, nByte);
  int actual = s21_memcmp(dataStr1, dataStr2, nByte);

  ck_assert_int_eq(expected, actual);



}
END_TEST

START_TEST(s21_memcmp_first_more_test)
{
  s21_size_t nByte = 5;
  char dataStr1[] = "Gekko";
  char dataStr2[] = "Hello";

  int expected = memcmp(dataStr1, dataStr2, nByte);
  int actual = s21_memcmp(dataStr1, dataStr2, nByte);

  ck_assert_int_eq(expected, actual);



}
END_TEST

START_TEST(s21_memcmp_second_more_test)
{
  s21_size_t nByte = 5;
  char dataStr1[] = "Hello";
  char dataStr2[] = "Gekko";

  int expected = memcmp(dataStr1, dataStr2, nByte);
  int actual = s21_memcmp(dataStr1, dataStr2, nByte);

  ck_assert_int_eq(expected, actual);



}
END_TEST

START_TEST(s21_memcmp_zero_byte_in_num)
{
  s21_size_t nByte = 0;
  char dataStr1[] = "1234";
  char dataStr2[] = "1234";

  int expected = memcmp(dataStr1, dataStr2, nByte);
  int actual = s21_memcmp(dataStr1, dataStr2, nByte);

  ck_assert_int_eq(expected, actual);



}
END_TEST

START_TEST(s21_memcmp_eq_long_string)
{
  s21_size_t nByte = 39;
  char dataStr1[] = "wugjdklfjgutyjdfghcgg 935923594 ($%@#$";
  char dataStr2[] = "wugjdklfjgutyjdfghcgg 935923594 ($%@#$";

  int expected = memcmp(dataStr1, dataStr2, nByte);
  int actual = s21_memcmp(dataStr1, dataStr2, nByte);

  ck_assert_int_eq(expected, actual);
}
END_TEST

START_TEST(s21_sprintf_format_char_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "Hello World %c";
  char dataOutput = 'c';

  int expectedInt = sprintf(expected, format, dataOutput);
  int actualInt = s21_sprintf(actual, format, dataOutput);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);


}
END_TEST

START_TEST(s21_sprintf_format_int_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "Hello World %d";
  int dataOutput = 616;

  int expectedInt = sprintf(expected, format, dataOutput);
  int actualInt = s21_sprintf(actual, format, dataOutput);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);


}
END_TEST

START_TEST(s21_sprintf_format_float_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "Hello World %f";
  double dataOutput = 234.76;

  int expectedInt = sprintf(expected, format, dataOutput);
  int actualInt = s21_sprintf(actual, format, dataOutput);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);


}
END_TEST

START_TEST(s21_sprintf_format_string_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "Hello World %s";
  char dataOutput[] = "Privet Mir";

  int expectedInt = sprintf(expected, format, dataOutput);
  int actualInt = s21_sprintf(actual, format, dataOutput);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);


}
END_TEST

START_TEST(s21_sprintf_format_unsigned_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "Unsigned number: %u";
  unsigned int dataOutput = 12345;

  int expectedInt = sprintf(expected, format, dataOutput);
  int actualInt = s21_sprintf(actual, format, dataOutput);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);


}
END_TEST

START_TEST(s21_sprintf_format_percent_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "Percent sign: %%";

  int expectedInt = sprintf(expected, format);
  int actualInt = s21_sprintf(actual, format);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);


}
END_TEST

START_TEST(s21_sprintf_format_flags_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "With flags: %+d % d";
  int dataOutput1 = 42;
  int dataOutput2 = 42;

  int expectedInt = sprintf(expected, format, dataOutput1, dataOutput2);
  int actualInt = s21_sprintf(actual, format, dataOutput1, dataOutput2);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);


}
END_TEST

START_TEST(s21_sprintf_format_width_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "Width: %10d";
  int dataOutput = 42;

  int expectedInt = sprintf(expected, format, dataOutput);
  int actualInt = s21_sprintf(actual, format, dataOutput);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);


}
END_TEST

START_TEST(s21_sprintf_format_precision_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "Precision: %.5f";
  double dataOutput = 3.14159;

  int expectedInt = sprintf(expected, format, dataOutput);
  int actualInt = s21_sprintf(actual, format, dataOutput);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);


}
END_TEST

START_TEST(s21_sprintf_format_length_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "Length: %ld";
  long dataOutput = 123456789L;

  int expectedInt = sprintf(expected, format, dataOutput);
  int actualInt = s21_sprintf(actual, format, dataOutput);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);


}
END_TEST

START_TEST(s21_sprintf_complex_format_test)
{
  char expected[SIZE];
  char actual[SIZE];

  char *format = "Complex: %+10.5f";
  double dataOutput = 3.14159;

  int expectedInt = sprintf(expected, format, dataOutput);
  int actualInt = s21_sprintf(actual, format, dataOutput);

  ck_assert_int_eq(expectedInt, actualInt);
  ck_assert_str_eq(expected, actual);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("test_s21_memchr");
    TCase *tc1_1 = tcase_create("test_s21_memchr");
    Suite *s2 = suite_create("test_s21_memcmp");
    TCase *tc2_1 = tcase_create("test_s21_memcmp");
    Suite *s3 = suite_create("test_s21_sprintf");
    TCase *tc3_1 = tcase_create("test_s21_sprintf");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_memchr_empty_str);
    tcase_add_test(tc1_1, s21_memchr_find_zero_in_stringt);
    tcase_add_test(tc1_1, s21_memchr_find_simbol_in_string_in_start);
    tcase_add_test(tc1_1, s21_memchr_find_simbol_in_string_in_end);
    tcase_add_test(tc1_1, s21_memchr_test_memchr_not_found);
    suite_add_tcase(s2, tc2_1);
    tcase_add_test(tc2_1, s21_memcmp_zero_byte);
    tcase_add_test(tc2_1, s21_memcmp_positive_test);
    tcase_add_test(tc2_1, s21_memcmp_first_more_test);
    tcase_add_test(tc2_1, s21_memcmp_second_more_test);
    tcase_add_test(tc2_1, s21_memcmp_zero_byte_in_num);
    tcase_add_test(tc2_1, s21_memcmp_eq_long_string);
    suite_add_tcase(s3, tc3_1);
    tcase_add_test(tc3_1, s21_sprintf_format_char_test);
    tcase_add_test(tc3_1, s21_sprintf_format_int_test);
    tcase_add_test(tc3_1, s21_sprintf_format_float_test);
    tcase_add_test(tc3_1, s21_sprintf_format_string_test);
    tcase_add_test(tc3_1, s21_sprintf_format_unsigned_test);
    tcase_add_test(tc3_1, s21_sprintf_format_percent_test);
    tcase_add_test(tc3_1, s21_sprintf_format_flags_test);
    tcase_add_test(tc3_1, s21_sprintf_format_width_test);
    tcase_add_test(tc3_1, s21_sprintf_format_precision_test);
    tcase_add_test(tc3_1, s21_sprintf_format_length_test);
    tcase_add_test(tc3_1, s21_sprintf_complex_format_test);

    srunner_add_suite(sr, s2);
    srunner_add_suite(sr, s3);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
